### ISSUE TITLE
How can I find the "3DViews Object Menu"?

### ISSUE THREAD

**Issue by KRK11** [D3ZAX/VrmToFBXWithTexture#1]

**Comment by D3ZAX** [comment]
It's the Sidebar of 3D Viewport, like the image showed, I will change the introduction.
![image](https://github.com/D3ZAX/VrmToFBXWithTexture/assets/15343372/151fa30d-4571-45ec-9fc6-219787bd1ae1)

**Comment by KRK11** [comment]
> 

ohh, thanks
